# Run this playbook corresponding with `local` group of hosts
---
- hosts: all
  roles:
    - base
  tags: boot

- hosts: ansible_pull_managed
  roles:
    - ivan-c.ansible-pull
  tags: boot

- hosts: headless_hosts
  tasks:
    - include_role:
        name: ivan-c.sumologic
      # skip if ansible-secrets repo absent
      when: lookup('file','/etc/opt/ansible-secrets/README.md', errors='ignore')
  tags: boot

- hosts: docker_hosts
  roles:
    - geerlingguy.docker

  # manually set distribution_major_version, until debian bookworm support available
  vars:
    ansible_distribution_release: '{{ "bullseye" if ansible_facts["distribution_major_version"] == "bookworm/sid" else ansible_facts["distribution_release"] }}'

    # todo: fix arm64 defaults when ansible_machine == aarch64
    docker_apt_arch: '{{ "arm64" if ansible_facts["machine"] == "aarch64" else "amd64" }}'
  post_tasks:
    - name: Use journald log driver for docker
      copy:
        content: '{"log-driver": "journald"}'
        dest: /etc/docker/daemon.json
      notify: restart docker
  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted

- hosts: gfx
  roles:
    - stream_host
    - amd_firmware
    - laptop

- hosts: htpc
  roles:
    - ivan-c.dell-u2713hm
    - hp_firmware
    - workstation
    - stream_client

- hosts: laptops
  roles:
    - laptop
    - workstation

- hosts: biostar_firmware
  roles:
    - biostar_firmware
