# Run this playbook corresponding with `local` group of hosts
---
- name: Install base roles
  hosts: all
  roles:
    - base
  tags: boot

- name: Install ansible-pull wrapper for managed hosts
  hosts: ansible_pull_managed
  roles:
    - ivan_c.ansible_pull
  tags: boot

- name: Install roles for collecting remote logs
  hosts: log_collection
  tasks:
    - name: Install remote logging role, if secrets configured
      ansible.builtin.include_role:
        name: ivan-c.sumologic
      # skip if ansible-secrets repo absent
      when: lookup('file', '/etc/opt/ansible-secrets/README.md', errors='ignore')
  tags: boot

- name: Install docker role
  hosts: docker_hosts
  roles:
    - geerlingguy.docker

  # manually set distribution_major_version, until debian bookworm support available
  vars:
    ansible_distribution_release: '{{ "bullseye" if ansible_facts["distribution_release"] == "bookworm" else ansible_facts["distribution_release"] }}'

    # todo: fix arm64 defaults when ansible_machine == aarch64
    docker_apt_arch: '{{ "arm64" if ansible_facts["machine"] == "aarch64" else "amd64" }}'
  post_tasks:
    - name: Use journald log driver for docker
      ansible.builtin.copy:
        content: '{"log-driver": "journald"}'
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0755
      notify: Restart docker
  handlers:
    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted


- name: Install roles for gfx hosts
  hosts: stream_host
  roles:
    - stream_host

- name: Install roles for GUI hosts
  hosts: gui
  roles:
    - gui

- name: Install roles for work
  hosts: work
  roles:
    - work

- name: Install roles for biostar hosts
  hosts: biostar_firmware
  roles:
    - biostar_firmware

- name: Install roles for HP hosts
  hosts: hp_firmware
  roles:
    - hp_firmware

- name: Install roles for AMD hosts
  hosts: amd_firmware
  roles:
    - amd_firmware
