# Run this playbook corresponding with `local` group of hosts
---
- hosts: all
  roles:
    - base
    - ansible_pull
  tags: boot

- hosts: headless_hosts
  tasks:
    - include_role:
        name: ivan-c.sumologic
      # skip if ansible-secrets repo absent
      when: lookup('file','/etc/opt/ansible-secrets/README.md', errors='ignore')
  tags: boot

- hosts: docker_hosts
  roles:
    - geerlingguy.docker

  # manually set distribution_major_version
  # workaround for debian buster (testing) bug
  # https://github.com/ansible/ansible/issues/19874#issuecomment-436542563
  vars:
    ansible_distribution_release: '{{ "buster" if ansible_facts["distribution_major_version"] == "buster/sid" else ansible_facts["distribution_release"] }}'

    # todo: fix arm64 defaults when ansible_machine == aarch64
    docker_apt_arch: '{{ "arm64" if ansible_facts["machine"] == "aarch64" else "amd64" }}'
  pre_tasks:
    - name: Install apt_key prerequisites
      package:
        name: gnupg
        state: present
  post_tasks:
    - name: Use journald log driver for docker
      copy:
        content: '{"log-driver": "journald"}'
        dest: /etc/docker/daemon.json
      notify: restart docker
  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted

- hosts: htpc
  roles:
    - ivan-c.dell-u2713hm
    - hp_firmware

- hosts: laptops
  roles:
    - laptop
