# Run this playbook corresponding with `local` group of hosts
---
- hosts: all
  roles:
    - debug

- hosts: docker_hosts
  roles:
    - geerlingguy.docker
  pre_tasks:
    - name: Install role dependencies
      command:
        ansible-galaxy install --role-file requirements.yaml
