# molecule config stub
# extends --base-config molecule/default/molecule.yml
---
platforms:
  - name: instance
    image: debian:10
    dockerfile: ../../../../molecule/default/Dockerfile.j2
provisioner:
  name: ansible
  playbooks:
    converge: ./playbook.yml
