# molecule config stub
# extends --base-config molecule/default/molecule.yml
---
platforms:
  - name: instance
    image: python:3
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ./converge.yml
