# molecule config stub
# extends --base-config molecule/default/molecule.yml
# required debian packages: libvirt-daemon-system vagrant vagrant-libvirt qemu qemu-utils qemu-kvm ebtables
---
platforms:
  - name: instance
    box: debian/buster64
    provider_options:
      # unquoted value raises exception
      # Message: NameError: undefined local variable or method `qemu' for main:Object
      driver: "'qemu'"
      emulator_path: "'/usr/bin/qemu-system-x86_64'"
      machine_arch: "'x86_64'"

driver:
  name: vagrant
  provider:
    name: libvirt
