---
- name: Install flatpak
  apt:
    name: flatpak

- name: Add the flathub flatpak repository remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  flatpak:
    name: "{{ item }}"
  with_items:
    - com.slack.Slack
    - us.zoom.Zoom
    - com.getpostman.Postman
