---
- name: Install flatpak apps
  ansible.builtin.import_tasks: flatpak.yaml

- name: Install workstation packages
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - chromium
      - curl
      - mosh
