# global molecule config
# to use this file as-is, set MOLECULE_GLOB environment variable to full path of this file
# to extend this file, pass `--base-config molecule/resources/scenarios/default/molecule.yml` to `molecule`
---
driver:
  name: docker
platforms:
  - name: instance
    # pin to current debian stable
    image: python:3-bullseye
    pre_build_image: true
    groups:
      # groups corresponding with external roles, not in the monorepo
      - docker_hosts
provisioner:
  name: ansible
  config_options:
    defaults:
      # TODO remove after upgrading from ansible 2.10
      # silence version warnings from community.docker collection built into molecule
      collections_on_ansible_version_mismatch: ignore

  playbooks:
    converge: ../../playbooks/converge.yml
