---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - aptitude
    - tasksel

- name: Install KDE
  command: tasksel --task-packages laptop 

- name: Install KDE
  command: aptitude install --assume-yes ~t^desktop$ ~t^kde-desktop$
