---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nfs-common

- name: Install flatpak apps
  ansible.builtin.import_tasks: flatpak.yaml
