---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nfs-common
      - steam-devices

- name: Install flatpak apps
  community.general.flatpak:
    name: "{{ item }}"
  with_items:
    - com.valvesoftware.Steam
    - org.DolphinEmu.dolphin-emu
