# molecule config stub
# extends --base-config molecule/default/molecule.yml
---
platforms:
  - name: instance
    # pin to current debian stable
    image: python:3-bullseye
    pre_build_image: true
    # zoom flatpak requires ability to create namespace
    privileged: true
provisioner:
  name: ansible
  playbooks:
    converge: ../../../../molecule/default/converge.yml
