# molecule config stub
# extends --base-config molecule/default/molecule.yml
---
driver:
  name: vagrant
  provider:
    # zoom flatpak requires ability to create namespace
    name: libvirt
  provision: true
platforms:
  - name: bullseye
    # pin to current debian stable
    box: debian/bullseye64
