# global molecule config
# set MOLECULE_GLOB environment variable to full path of this file
---
driver:
  name: docker
platforms:
  - name: instance
    # pin to current debian stable
    image: python:3-bullseye
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      # TODO remove after upgrading from ansible 2.10
      # silence version warnings from community.docker collection built into molecule
      collections_on_ansible_version_mismatch: ignore
