# global molecule config
# set MOLECULE_GLOB environment variable to full path of this file
---
driver:
  name: docker
platforms:
  - name: instance
    # TODO pin to current debian stable
    image: python:3
    pre_build_image: true
provisioner:
  name: ansible
