---
driver:
  name: docker
platforms:
  - name: bullseye
    # pin to current debian stable
    image: python:3-bullseye
    pre_build_image: true
    groups:
      - amd_firmware
      - log_collection
      - stream_host
      - gui
      - hp_firmware
