# molecule config stub
# extends --base-config molecule/default/molecule.yml
---
platforms:
  - name: instance
    image: debian:10
    dockerfile: ../../../../molecule/default/Dockerfile.j2
    # zoom flatpak requires ability to create namespace
    privileged: true
provisioner:
  name: ansible
  playbooks:
    converge: ../../../../molecule/default/playbook.yml
