---
- name: Install required packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - software-properties-common

- name: Add non-free sources
  command: apt-add-repository non-free
  register: add_component_result
  notify:
    - Update package lists
  changed_when: '"component enabled" in add_component_result.stdout'

- name: Flush all notified handlers
  meta: flush_handlers

# Wake-on-LAN requires the following BIOS settings:
# EuP Control must be disabled
# PME Wake up from S5 must be enabled
- name: Install firmware and driver necessary for Wake-on-LAN
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - firmware-realtek
      - "{{ kernel_headers_package }}"
      # TODO dynamically load r8168 only before poweroff (use r8169 otherwise)
      - r8168-dkms
