---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - software-properties-common

- name: Add non-free sources
  ansible.builtin.command: apt-add-repository non-free
  register: add_component_result
  notify:
    - Update package lists
  changed_when: '"component enabled" in add_component_result.stdout'

- name: Flush all notified handlers
  ansible.builtin.meta: flush_handlers

- name: Install required firmware
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - firmware-atheros
      - firmware-realtek
