---
name: ⚛️Molecule testing
on: [push]
jobs:
  molecule-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Update package metadata
        run:  sudo apt-get update

      - name: Install vagrant and libvirt packages
        run:
          sudo apt-get install --no-install-recommends
            libvirt-daemon-system
            vagrant-libvirt
            qemu-kvm
            libguestfs-tools

        # HACK molecule does not emit colored output with sudo
      - name: Allow any user to run libvirt
        run: sudo chmod o+rw /var/run/libvirt/libvirt-sock

      - name: Install test runner
        run: python3 -m pip install tox

      - name: Set and run tox environments
        # test every role in roles/ directory
        run: tox
        env:
          # force color output
          # https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci
          ANSIBLE_FORCE_COLOR: 1
